export const json = [
  {
    id: "c13fe3d1-9126-41bd-af27-5b7a7e39c9fc",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Snow Roth",
    company: "GEEKMOSIS",
    email: "snowroth@geekmosis.com",
    phone: "+1 (825) 596-3855",
    address: "641 Crosby Avenue, Jacksonwald, Arkansas, 2355",
    skills: ["duis", "incididunt", "ipsum", "ullamco"],
  },
  {
    id: "a12f60ea-fa0f-40c4-9cf6-77304464029a",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Copeland Monroe",
    company: "GENMEX",
    email: "copelandmonroe@genmex.com",
    phone: "+1 (920) 599-3903",
    address:
      "288 Durland Place, Albrightsville, Federated States Of Micronesia, 9062",
    skills: ["eiusmod", "excepteur", "velit", "minim"],
  },
  {
    id: "e29df096-600b-4ed7-a8a6-db11c9c4fa6d",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Katie Conner",
    company: "VISUALIX",
    email: "katieconner@visualix.com",
    phone: "+1 (988) 590-2098",
    address: "568 Cypress Court, Henrietta, Mississippi, 1012",
    skills: ["ex", "magna", "nisi", "culpa"],
  },
  {
    id: "f6d011dc-d6a2-4e38-8b5e-1cac37e70cae",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Stewart Hyde",
    company: "COMVENE",
    email: "stewarthyde@comvene.com",
    phone: "+1 (803) 537-3454",
    address: "281 Montana Place, Muse, Delaware, 391",
    skills: ["magna", "ea", "et", "exercitation"],
  },
  {
    id: "310c4ddd-61b5-4f69-bf02-7b4753b14889",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Alicia Guzman",
    company: "PLASMOS",
    email: "aliciaguzman@plasmos.com",
    phone: "+1 (882) 554-2991",
    address: "545 Newport Street, Datil, Idaho, 6155",
    skills: ["occaecat", "laboris", "est", "do"],
  },
  {
    id: "23b232c5-cab4-4cd2-88eb-bba1c3fb41e8",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Dickerson Christensen",
    company: "PROXSOFT",
    email: "dickersonchristensen@proxsoft.com",
    phone: "+1 (801) 564-2184",
    address: "852 Union Street, Morriston, Virginia, 5213",
    skills: ["veniam", "id", "sunt", "minim"],
  },
  {
    id: "890b042a-c384-40dc-8347-aba64eefc692",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Valenzuela Dale",
    company: "DELPHIDE",
    email: "valenzueladale@delphide.com",
    phone: "+1 (919) 492-3542",
    address: "577 Bowery Street, Woodlands, Utah, 9702",
    skills: ["ullamco", "nostrud", "reprehenderit", "labore"],
  },
  {
    id: "262725d6-67d0-4c41-b999-22d9379a8f1c",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Cochran Hayes",
    company: "UTARA",
    email: "cochranhayes@utara.com",
    phone: "+1 (956) 525-2384",
    address: "723 Strong Place, Tuskahoma, Wisconsin, 2314",
    skills: ["do", "do", "duis", "excepteur"],
  },
  {
    id: "42658777-8882-42db-8eae-8064e00d27e3",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Rowland Tyler",
    company: "APPLICA",
    email: "rowlandtyler@applica.com",
    phone: "+1 (897) 427-3111",
    address: "954 Post Court, Mansfield, California, 7389",
    skills: ["duis", "laboris", "mollit", "ut"],
  },
  {
    id: "c55f976d-a451-4ae6-b2db-f742cb03249f",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Doreen Poole",
    company: "ARTWORLDS",
    email: "doreenpoole@artworlds.com",
    phone: "+1 (901) 473-3126",
    address: "497 Pierrepont Street, Iola, New Hampshire, 8569",
    skills: ["commodo", "officia", "laborum", "sit"],
  },
  {
    id: "60b999d0-6227-4e39-aab8-f6cac904de1f",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Mcfarland Pitts",
    company: "MAGNAFONE",
    email: "mcfarlandpitts@magnafone.com",
    phone: "+1 (996) 506-3835",
    address: "838 Williams Place, Camptown, Kansas, 1993",
    skills: ["dolor", "deserunt", "sunt", "consectetur"],
  },
  {
    id: "fe2bd61f-c45e-475c-ae3d-cc9b442ac0e3",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Bates Wiley",
    company: "KYAGURU",
    email: "bateswiley@kyaguru.com",
    phone: "+1 (912) 531-2447",
    address: "267 Schenectady Avenue, Forestburg, Texas, 4346",
    skills: ["adipisicing", "exercitation", "fugiat", "minim"],
  },
  {
    id: "494b08c9-b753-418b-b594-96be01dbfa72",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Chase Edwards",
    company: "EXPOSA",
    email: "chaseedwards@exposa.com",
    phone: "+1 (876) 425-2674",
    address: "949 Blake Avenue, Martinez, Marshall Islands, 4161",
    skills: ["exercitation", "deserunt", "aute", "velit"],
  },
  {
    id: "02548612-83e7-40bc-af77-176312a0d63f",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Caroline Anderson",
    company: "ZENOLUX",
    email: "carolineanderson@zenolux.com",
    phone: "+1 (836) 583-3528",
    address: "120 Dover Street, Aurora, Washington, 1947",
    skills: ["ullamco", "consequat", "eu", "sint"],
  },
  {
    id: "1d23f482-ed99-4209-ad8a-a88592e06f31",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Carrillo Kelley",
    company: "MOBILDATA",
    email: "carrillokelley@mobildata.com",
    phone: "+1 (896) 585-2747",
    address: "568 Bushwick Court, Hachita, Kentucky, 8803",
    skills: ["officia", "cupidatat", "commodo", "dolore"],
  },
  {
    id: "0facaf10-6d89-4089-aa8f-f34587ca1707",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Vilma Rosario",
    company: "EXOSTREAM",
    email: "vilmarosario@exostream.com",
    phone: "+1 (976) 539-3426",
    address: "261 Polhemus Place, Idledale, District Of Columbia, 281",
    skills: ["incididunt", "voluptate", "consequat", "ullamco"],
  },
  {
    id: "fc852e5a-fe55-4aa9-9ff0-0c530ec17af9",
    picture:
      "https://preview.keenthemes.com/metronic-v4/theme/assets/pages/media/profile/profile_user.jpg",
    name: "Myrna Waters",
    company: "MOTOVATE",
    email: "myrnawaters@motovate.com",
    phone: "+1 (820) 454-3678",
    address: "205 Rutherford Place, Mayfair, Florida, 689",
    skills: ["sit", "occaecat", "nostrud", "minim"],
  },
];
